services:
  mysql:
    image: mysql:8.0
    container_name: mysql_projet
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: projet
      MYSQL_USER: projet
      MYSQL_PASSWORD: projet
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    # healthcheck:
    #   test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$MYSQL_ROOT_PASSWORD"]
    #   interval: 5s
    #   timeout: 5s
    #   retries: 10

volumes:
  mysql_data: