version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: mysql_projet
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: projet_db
      MYSQL_USER: projet
      MYSQL_PASSWORD: projet
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: