# See http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
spring:
  thymeleaf:
    cache: false
  main:
    show-banner: false
  datasource:
    url: jdbc:mysql://localhost:3306/projet_db?useSSL=false&serverTimezone=UTC
  datasource:
    username: projet
    password: projet
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

