# See http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
spring:
  thymeleaf.cache: false
  main.show-banner: false

  docker:
    compose:
      enabled: true
      lifecycle-management: start_only
      skip:
        in-tests: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://localhost:3306/projet
    username: projet
    password: projet
    driver-class-name: com.mysql.cj.jdbc.Driver